[stable/yugaware] service annotation indentation
yugabyte/charts-helm-fork pull request #13
Opened 2019-08-21 22:56 UTC by aegershman

https://github.com/YugaByte/yugabyte-db/issues/1338#issuecomment-523676862

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-23 18:51 UTC, ramkumarvs reviewed
One comment, otherwise looks good.

2019-08-23 18:51 UTC, ramkumarvs commented on stable/yugaware/templates/service.yaml
> +    {{- range $key, $value := .Values.yugaware.service.annotations }}
@aegershman can we just update the indent to achieve this instead of looping through the annotations?

2019-08-23 19:56 UTC, ramkumarvs commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
also i would keep the version as is, since we keep our appVersion to match the chart version

2019-08-23 20:13 UTC, ramkumarvs requested changes
if you can address my comments, i can accept this change. Also feel free to add yourself as one of the maintainers to the charts.yaml

2019-08-23 20:13 UTC, ramkumarvs commented on stable/yugaware/templates/service.yaml
> +    {{- range $key, $value := .Values.yugaware.service.annotations }}
@aegershman so the actual change should be something as simple as indenting the annotations under the metadata instead of label. And the indent should be 4 instead of 6.

2019-08-24 00:56 UTC, aegershman commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
[The chart version needs to bump on every change, even if it's just documentation or README changes](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#immutability). Otherwise it's overwriting the same semver. That's the reasoning for having `version` and `appVersion` as separate params. It's normal for charts to bump versions while still having the same appVersion. But no matter what the same [chart version can't be overwritten](https://github.com/YugaByte/yugabyte-db/issues/1327) because it breaks immutability

2019-08-26 20:12 UTC, ramkumarvs commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
Aaron, understand, but bumping the third digit without bumping corresponding appVersion might break our release flow, if it makes sense, i would wait for the 1.3.3.x version of the app be available before we land this change.

2019-08-26 21:03 UTC, aegershman commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
I think this will be painful for everyone if the appVersion and chart version _have_ to match; improvements and bugfixes will have to change at some point-- like right now-- and if the appVersion and chart version are bound together there's no choice but to fork the chart and make changes locally; without doing so, the chart can't provision a load balancer. And we can't wait for a whole new release of the appVersion for a bug fix.

Maybe is there a concern with bumping the chart version because it makes it harder to release in bundles in places like `pivnet`? If so I'm not sure what to do about that, or if it even makes sense to have it be bundled within pivnet at all. Tiles like the [mongo enterprise db broker](https://network.pivotal.io/products/mongodb-enterprise-service/) only come with the service broker & assume that the "enterprise operations manager" is installed/deployed separately. So maybe it makes more sense to have yugaware be entirely separate from other release toolchains like `pivnet` and installed through a separate helm charts repo process. I'm not sure. I'm a bigger fan of having it separate from pivnet altogether, to be honest, so that no one has to worry about the _distribution_ of the yugaware chart to pivnet; it's handled in a separate process. But again, I don't know? I'd much rather the chart be entirely removed from the `pivnet` release process if it means the chart version in this repo can be updated more freely. We're pulling this chart directly from this charts repo rather than pivnet anyway, so if it has to be removed from pivnet so that the release process allows the chart version to change independently of the appVersion then so be it. We don't use it there currently anyway (but maybe others do?). And I don't know if that's actually a problem or not; maybe releasing the chart to pivnet is completely irrelevant to the release process, so I'm just pontificating

regardless, until the appversion and chart version can move independently, we'll have to fork the chart and make local changes & use that; we can't wait until a new appversion release and we can't overwrite the current chart version semver. until then we're either stuck or will have to use an internal fork

thoughts? 👍

2019-08-26 21:59 UTC, ramkumarvs commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
Yeah our concern is how we keep pivnet version and also other places, given helm chart doesn't support 4th digit since it is not semver is what makes it even difficult, let me sync up internally about this and get back to you.

2019-08-27 16:30 UTC, aegershman commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
Does pivnet require the helm chart for yugaware to be packaged w/ the broker? I vaguely recall pivotal's legal team requiring it? Apologies we can also talk about it offline later if you'd like.

2019-08-27 17:00 UTC, ramkumarvs approved these changes

2019-08-27 17:00 UTC, ramkumarvs commented on stable/yugaware/Chart.yaml
> -version: 1.3.2
@aegershman hey chatted internally with the team, and we all agree we need to bump the chart version as you pointed out, but given we want to keep our version (3 digits) to be inline with our stable release version. I am proposing any changes before that we will have committers tag them prerelease-X. so for this revision the version would be 1.3.2-prerelease-1

2019-09-25 16:19 UTC, closed without merging