Update to add busybox sidecar for log cleanup
yugabyte/charts-helm-fork pull request #40
Opened 2019-10-25 22:47 UTC by Arnav15

Updating the helm chart to address issue (https://github.com/yugabyte/yugabyte-db/issues/1487). This PR also sets sysctl values.
Tested by creating a custom YB container image with the log cleanup script packaged and verified that the pods come up with the sidecar and the sidecar has the cronjob running to clean up the logs. Verified the script itself by creating placeholder logs and verifying that they get cleared with every run.

2019-10-31 18:58 UTC, bmatican requested changes

2019-10-31 18:58 UTC, bmatican commented on stable/yugabyte/templates/service.yaml
> +                  mkdir -p /mnt/disk0/yb-data/scripts;
Should `/mnt/disk0/` be some generic var that a user could override?

2019-10-31 18:58 UTC, bmatican commented on stable/yugabyte/templates/service.yaml
> +            sysctl -w kernel.core_pattern="/home/yugabyte/cores/core_%e.%p"
This symlink is generated by our docker image, right? Is it hardcoded right now to `/mnt/disk0`? Should we switch to having that be generated in the `postStart`, so we could make it a var?

2019-10-31 18:58 UTC, bmatican commented on stable/yugabyte/templates/service.yaml
> +                    cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
ditto on vars for paths

2019-10-31 18:58 UTC, bmatican commented on stable/yugabyte/templates/service.yaml
> +            mountPath: /home/yugabyte/
ah nice, so this now matches the default home var value from the cleanup script, right?

2019-10-31 23:19 UTC, Arnav15 commented on stable/yugabyte/templates/service.yaml
> +                  mkdir -p /mnt/disk0/yb-data/scripts;
We can make it a generic var, but the dockerfile does hard-code the volumes, so maybe it won't be a good idea.

2019-10-31 23:23 UTC, Arnav15 commented on stable/yugabyte/templates/service.yaml
> +            sysctl -w kernel.core_pattern="/home/yugabyte/cores/core_%e.%p"
Sure, but we'll need to decide on how we would want to move forward with the corresponding changes to the dockerfile and what it would mean for the previous docker releases.

2019-10-31 23:23 UTC, Arnav15 commented on stable/yugabyte/templates/service.yaml
> +            mountPath: /home/yugabyte/
Yes, it now mimics the home directory path for all the other deployments.

2019-11-12 19:49 UTC, bmatican approved these changes
Make sure you mark in the title/description that you're also taking care of swappiness and cores

2019-11-12 19:49 UTC, bmatican commented on stable/yugabyte/Chart.yaml
> +appVersion: 2.0.4.0-b7
do we need to include this with the change?

2019-11-12 19:49 UTC, bmatican commented on stable/yugabyte/app-readme.md
> +This chart bootstraps an RF3 Yugabyte DB version 2.0.4.0-b7 cluster using the Helm Package Manager.
this feels cumbersome to always bump the version in text here too...

2019-11-13 04:21 UTC, merged