Added kube state metrics config in prometheus.
yugabyte/charts-helm-fork pull request #42
Opened 2019-11-20 21:36 UTC by Arnav15

Add ability to query kube_state_metrics in Kubernetes clusters.

2019-11-21 06:44 UTC, ramkumarvs requested changes
can you also bump the chart version and image tag?

2019-11-21 06:44 UTC, ramkumarvs commented on stable/yugaware/templates/configs.yaml
> +        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
what if the cluster domain name is different?

2019-11-21 06:44 UTC, ramkumarvs commented on stable/yugaware/templates/configs.yaml
> +      - job_name: 'kube-state-metrics'
do we need any changes to our RBAC permissions to query kube state metrics?

2019-11-21 22:56 UTC, Arnav15 commented on stable/yugaware/templates/configs.yaml
> +        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
Addressed comment.

2019-11-21 22:57 UTC, Arnav15 commented on stable/yugaware/templates/configs.yaml
> +      - job_name: 'kube-state-metrics'
No, that can be setup when bringing up the kube_state_metrics service.

2019-11-22 02:34 UTC, ramkumarvs approved these changes

2019-11-22 02:34 UTC, merged