Add a 'storage.enabled' knob.
yugabyte/charts-helm-fork pull request #53
Opened 2020-02-25 13:05 UTC by ghaskins

Many charts provide a 'persistence.enabled' feature, which is helpful in certain circumstances
such as ephemeral integration tests, where the use case does not warrant persistence but
does value quick startup and a comprehensive cleanup.

This patch adds a similar feature under the 'storage' section.

Signed-off-by: Greg Haskins <greg@manetu.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2020-02-25 22:30 UTC, rkarthik007 commented
Hi @ghaskins,

Thanks for your contribution! Could you please add yourself to the list of YugabyteDB contributors here: https://github.com/yugabyte/yugabyte-db/blob/master/CONTRIBUTORS.md

I have added some folks that can review and help merge this diff. Thanks once again!

2020-02-25 22:52 UTC, ghaskins commented
https://github.com/yugabyte/yugabyte-db/pull/3739

2020-03-03 19:23 UTC, ramkumarvs reviewed
@ghaskins thanks for the contribution, we will review this PR today and give you feedback.

2020-03-03 21:06 UTC, iSignal commented on stable/yugabyte/values.yaml
> +  enabled: true
I would suggest naming this 'ephemeral' instead of enabled. so 
 ` ephemeral: false` instead of enabled: true

2020-03-13 00:11 UTC, iSignal requested changes
@ghaskins : could you make the minor rename suggested below and we are good to go, thanks!

2020-04-13 03:11 UTC, ghaskins commented on stable/yugabyte/values.yaml
> +  enabled: true
will do, sorry missed this note

2020-04-13 03:33 UTC, ghaskins commented
@iSignal made the suggested change.

2020-04-13 21:30 UTC, iSignal approved these changes

2020-04-13 21:31 UTC, merged

2020-04-13 21:32 UTC, iSignal commented
Thank you for your contribution @ghaskins !