fix: disable privileged operations
yugabyte/charts-helm-fork pull request #58
Opened 2020-04-25 14:57 UTC by hstenzel

Privileged operations are disabled by default. They can be enabled
with a value.

This fixes the following bugs:
- As a developer without cluster-admin, I cannot deploy yugabyte
- As a cluster-admin, I can only deploy a single yugabyte instance
  of yugabyte in my cluster

Signed-off-by: Harley Stenzel <hstenzel@manetu.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2020-04-25 15:33 UTC, rkarthik007 commented
Hi @hstenzel,

Thanks for your contribution! Have added @ramkumarvs, @Arnav15 and @iSignal who can review.

Could you please add yourself to the Yugabyte contributors list: https://github.com/yugabyte/yugabyte-db/blob/master/CONTRIBUTORS.md

2020-04-25 19:21 UTC, hstenzel commented
@rkarthik007 I've updated the contributors https://github.com/yugabyte/yugabyte-db/pull/4303

2020-04-25 19:32 UTC, rkarthik007 commented
> @rkarthik007 I've updated the contributors [yugabyte/yugabyte-db#4303](https://github.com/yugabyte/yugabyte-db/pull/4303)

Thanks @hstenzel! And welcome to the Yugabyte contributor community 🎉🍾🔥!!

2020-04-30 11:08 UTC, bhavin192 requested changes
The change related to privileged container looks good to me, thank you for sending in the PR for that. I have added few comments, please take a look.

2020-04-30 11:08 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
> +# and should default to off.
You are right, I'm trying to address this in a separate PR as it needs to be tested on both OpenShift and Kubernetes. Possible for you to just revert this change related to cluster-admin and I will address it in a separate PR?

2020-04-30 11:08 UTC, bhavin192 commented on stable/yugabyte/values.yaml
> +  enabled: false
I think we should keep this `true` otherwise it will break the workflow for people who are already using privileged container in their installed release.

2020-05-04 19:53 UTC, iSignal commented
Hello @hstenzel , we are working on a change which will remove the privileged operations and the need for ClusterRoleBinding on the helm 3 yugabyte chart. Please feel free to abandon this PR and we will update this chart shortly to address this issue.

2020-05-05 18:56 UTC, iSignal commented
Hello @hstenzel, another update : the underlying issue should be addressed by the merge of this PR https://github.com/yugabyte/charts/pull/60 from @Arnav15 

Please let us know if you are still experiencing issues deploying this helm chart without a cluster-admin role, either here or by filing a new github issue.

2020-05-06 13:31 UTC, hstenzel commented
Thanks. I see that #60 removed the problematic sections for all, making this PR obsolete. IMO it's the right thing to do and is better than leaving the privileged in but protected by a value.

I'm closing this PR, but if that's the wrong thing to do please feel free to reopen it.

2020-05-06 13:31 UTC, closed without merging